// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sms} from '../models';

export function AddStudent(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string):Promise<number>;

export function CreateClass(arg1:string,arg2:number):Promise<{[key: string]: any}>;

export function DeleteClass(arg1:number):Promise<void>;

export function DeleteStudent(arg1:string,arg2:number):Promise<void>;

export function GenerateAndDownloadPDF(arg1:string,arg2:string,arg3:number,arg4:number):Promise<{[key: string]: any}>;

export function GetClass(arg1:number):Promise<sms.ClassInfo>;

export function Greet(arg1:string):Promise<string>;

export function ListClasses():Promise<Array<sms.ClassInfo>>;

export function ListStudents12(arg1:string):Promise<Array<sms.Student12>>;

export function ListStudents345(arg1:string):Promise<Array<sms.Student345>>;

export function UpdateClass(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpdateStudent12(arg1:string,arg2:number,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number,arg11:number,arg12:number,arg13:number,arg14:number,arg15:number,arg16:number,arg17:number,arg18:number,arg19:number,arg20:number):Promise<void>;

export function UpdateStudent345(arg1:string,arg2:number,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number,arg11:number,arg12:number,arg13:number,arg14:number,arg15:number,arg16:number,arg17:number,arg18:number,arg19:number,arg20:number,arg21:number,arg22:number,arg23:number,arg24:number,arg25:number,arg26:number,arg27:number,arg28:number,arg29:number,arg30:number,arg31:number,arg32:number):Promise<void>;
