// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStudent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateClass(arg1, arg2) {
  return window['go']['main']['App']['CreateClass'](arg1, arg2);
}

export function DeleteClass(arg1) {
  return window['go']['main']['App']['DeleteClass'](arg1);
}

export function DeleteStudent(arg1, arg2) {
  return window['go']['main']['App']['DeleteStudent'](arg1, arg2);
}

export function GenerateAndDownloadPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateAndDownloadPDF'](arg1, arg2, arg3, arg4);
}

export function GetClass(arg1) {
  return window['go']['main']['App']['GetClass'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListClasses() {
  return window['go']['main']['App']['ListClasses']();
}

export function ListStudents12(arg1) {
  return window['go']['main']['App']['ListStudents12'](arg1);
}

export function ListStudents345(arg1) {
  return window['go']['main']['App']['ListStudents345'](arg1);
}

export function UpdateClass(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateClass'](arg1, arg2, arg3);
}

export function UpdateStudent12(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20) {
  return window['go']['main']['App']['UpdateStudent12'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20);
}

export function UpdateStudent345(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, arg32) {
  return window['go']['main']['App']['UpdateStudent345'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, arg32);
}
